# settings.py

# Path to the PDF file
PDF_PATH = "data/HSC26_Bangla_1st_Paper.pdf"

# Directory where vectorstore is saved
VECTORSTORE_DIR = "vectorstore/"

# Embedding model to use
EMBEDDING_MODEL_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

# Chunking settings
CHUNK_SIZE = 500
CHUNK_OVERLAP = 50

# Retrieval settings
TOP_K = 3

# LLM (optional if using OpenAI)
OPENAI_MODEL_NAME = "gpt-3.5-turbo"
